/**
 * OpenAIEmbeddingProvider — Fallback embedding implementation
 *
 * Used ONLY when Ollama fails (e.g. not running, model not pulled).
 * Intentionally minimal — mirrors text-embedding-3-small at 1536 dims.
 *
 * NOTE: The OpenAI embedding model (1536-dim) produces a different
 * vector space than Ollama's nomic-embed-text (768-dim). Mixing both
 * in the same pgvector column requires the column to be sized at the
 * larger dimension (1536). Since the database already uses 1536,
 * the fallback is safe. However, vectors generated by different models
 * are NOT cross-comparable — similarity searches should be consistent
 * within a session.
 *
 * Configuration:
 *   OPENAI_API_KEY   — required for this fallback to activate
 */

import { Logger } from '@nestjs/common';
import OpenAI from 'openai';
import { EmbeddingProvider } from './embedding-provider.interface';

interface OpenAIEmbeddingConfig {
  apiKey: string;
  model?: string;
  dimensions?: number;
}

export class OpenAIEmbeddingProvider implements EmbeddingProvider {
  private readonly logger = new Logger(OpenAIEmbeddingProvider.name);
  private readonly client: OpenAI;
  private readonly model: string;
  private readonly dimensions: number;

  constructor(config: OpenAIEmbeddingConfig) {
    this.client = new OpenAI({ apiKey: config.apiKey });
    this.model = config.model ?? 'text-embedding-3-small';
    this.dimensions = config.dimensions ?? 1536;
  }

  async embed(text: string): Promise<number[]> {
    const truncated = text.slice(0, 30_000); // OpenAI token limit safety

    const response = await this.client.embeddings.create({
      model: this.model,
      input: truncated,
      dimensions: this.dimensions,
    });

    const vector = response.data[0]?.embedding;
    if (!vector || vector.length === 0) {
      throw new Error('OpenAI returned an empty embedding vector');
    }

    this.logger.debug(
      `[Embedding] OpenAI fallback generated ${vector.length}-dim vector (model=${this.model})`,
    );

    return vector;
  }
}
