server {
    listen 443 ssl;
    server_name bestpurchasestore.com www.bestpurchasestore.com;

    ssl_certificate /etc/letsencrypt/live/bestpurchasestore.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bestpurchasestore.com/privkey.pem;

    # 🔐 security
    location ~ /\.(env|git) {
        deny all;
        return 403;
    }

    # frontend
    location / {
        proxy_pass http://crm_web_green:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # api
    location /api/ {
        proxy_pass http://crm_api_green:3001;
    }
}
